### ISSUE TITLE
Use figcaption, not caption

### ISSUE THREAD

**Issue by oliverjam** [fac21/week1-Digital-Agency-Project-AJMS#30]
https://github.com/fac21/week1-Digital-Agency-Project-AJMS/blob/dbbf2ca6fbbffecba9ea8e92d71ccb0486ddaac6/index.html#L48-L53

It's confusing, but the [`<caption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) element is for adding captions to `<table>`s. For `<figure>`s you want the [`<figcaption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) element.

**Comment by designaky** [comment]
Closes #30

**Comment by oliverjam** [comment]
@designaky I'm not sure if you meant to close this? Is the issue already fixed?
